print("Hello, Welcome to the coding universe")
name = input("What would you like us to call you?: ")
print(f"We are pleased you could join us, {name}")
age = int(input(f"What is your current age, {name}?: "))
feedback = input("Why would you like to enter the coding universe?: ")
print("Lets us begin!")
